FROM node:10.15-alpine
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install
RUN npm i -g @angular/cli@7.2.2
COPY . .
EXPOSE 4200 49153
CMD ["ng", "serve", "--port", "4200", "--host", "0.0.0.0", "--poll", "1"]