version: '3.4'

services:
  integration-tests:
    image: rabbly-integration
    container_name: rabbly-integration
    build:
      context: .
      dockerfile: Api/tests/integration-tests/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - 5001:5001
    volumes:
      - ./Api/tests/integration-tests:/src/test
      - ./Api/src:/src/api
